#!/usr/bin/env bash
# loops from 1 to 10 using while loop to display "bad luck" at the 4th iteration, "good luck" at the 8 iteration and "Best School" for the other iterations.
counter=0
while [ $counter -lt 10 ]; do
	(( counter+=1 ))
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
